### ISSUE TITLE
Code is not usable or documented

### ISSUE THREAD

**Issue by DNA2RNA** [octavian-ganea/equidock_public#23]
The code does not work. There is no documentation. Please provide a working example.

**Comment by sherryliu987** [comment]
If you're struggling to run EquiDock locally, feel free to try https://www.tamarind.bio/equidock. Tamarind is an online platform for bioinformatics tools that offers structural biology workflows, including EquiDock, for free.

**Comment by DNA2RNA** [comment]
I love the work and raised an issue b/c I thought it might be an important tool for which accessibility should be prioritized. Open-source science that lacks examples reduces accessibility and reproducibility–core tenets of quality scientific tools. The implementation I commented on didn’t seem accessible to newbies or users wanting to run quick tests locally. If you care about accessibility and facilitating reproducibility, then I’d encourage EquiDock to provide minimal working examples, inviting broader exploration.
