### ISSUE TITLE
error when I run preprocess_raw_data.py. How can I fix it?

### ISSUE THREAD

**Issue by mycode-bit** [octavian-ganea/equidock_public#3]
hello, 
when I run the command: python preprocess_raw_data.py -n_jobs 20 -data db5 -graph_nodes residues -graph_cutoff 30 -graph_max_neighbor 10 -graph_residue_loc_is_alphaC -pocket_cutoff 8
**********************************
I got the following error:
***************************
Processing split  1
Processing  ./cache/db5_residues_maxneighbor_10_cutoff_30.0_pocketCut_8.0/cv_1\label_val.pkl
Traceback (most recent call last):
  File "C:\Users\equidock_public-main\src\preprocess_raw_data.py", line 37, in <module>
    Unbound_Bound_Data(args, reload_mode='val', load_from_cache=False, raw_data_path=raw_data_path,
  File "C:\Users\equidock_public-main\src\utils\db5_data.py", line 78, in __init__
    with open(os.path.join(split_files_path, reload_mode + '.txt'), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/benchmark5.5/cv/cv_0\\cv_1\\val.txt'

Any suggestions?

Thanks

**Comment by octavian-ganea** [comment]
Ups, thanks for this. The current code only works for a single split. I just pushed this modification. If you want to do cross validation on multiple splits, you would have to modify the code. Also, I notice that you are using a Windows machine, but the current code is using the Linux/Mac file paths with forward slashes. You would need to adjust the code for Windows.

**Comment by mycode-bit** [comment]
Thanks. That works.

I have another question regarding how to run it:
***********************************
I have run through your instruction, it seems all about processing data, training etc. 
Can I just use the pre-trained model to do docking? 
What is the actual command do I need to run with my own pdb? 
I may miss something here. 
Appreciate your help.
Thanks

**Comment by octavian-ganea** [comment]
You can use our pretrained models. Just check inference_rigid.py and our instructions in the README.

**Comment by mycode-bit** [comment]
got it. thanks
