### ISSUE TITLE
deallock in make_dataset

### ISSUE THREAD

**Issue by lizhenping** [octavian-ganea/equidock_public#7]
as we can see in the DISP_Plus, the author said: about make dips dataset #7
https://github.com/BioinfoMachineLearning/DIPS-Plus/issues/7

"deadlock of sorts after a certain number of complexes have been processed."
when run for a long time, it will appeare By chance，
but for few files , it always run success, so i Split up to process the make_dataset

first mkdir six different fold like tmp1 tmp2 ....
mkdir tmp1
than cd in pdb and move the files to the new fold
mv `ls | head -200` ../tmp6
run make_dataset.py seperate:
python3 make_dataset.py project/datasets/DIPS/raw/tmp1 project/datasets/DIPS/interim --num_cpus 24 --source_type rcsb --bound

**Comment by lizhenping** [comment]
when install the dgl , it can't directly used pip install dgl, it will install a cpu version
used the script in 
https://www.dgl.ai/pages/start.html

**Comment by lijiashan2020** [comment]
#9 
@zhenpingli I'm sorry to bother you, but I learned that you're also trying to run equidock. I'd like to ask if you encounter the situation that three files ``` *_graph_frac_1.0_train.bin``` cannot be generated when running the script ```preprocess_raw_data.py```. Although the command cannot be used in datasets DIPs_ Plus, but it seems that the required files can be generated normally on DB5. When dealing with DIPs_Plus datasets, I have learned from your ideas and benefited a lot. I wonder if you have a solution about this question.
Thanks!

**Comment by octavian-ganea** [comment]
No need to run the make_dataset code, I just uploaded the DIPS dataset, see dropbox link in the readme.
